### ISSUE TITLE
Develop preprocessing script for legislation from The Gambia

### ISSUE THREAD

**Issue by danpdraper** [danpdraper/eia#21]

**Comment by Skyrolon** [comment]
The legislation under [FAOLEX](https://www.fao.org/faolex/results/details/en/c/LEX-FAOC006275) is very poorly OCRed. There is a much better version in the related resources section under the same FAOLEX link. As far as I can tell these two documents represent the same piece of legislation. Just wanted to confirm if I can use the version under the related resources section instead of the main document.

**Comment by danpdraper** [comment]
Yes, those two documents should encapsulate the same piece of legislation, so feel free to use the document in the related resources section.
